/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminVaultIdRouteImport } from './routes/admin/$vaultId'
import { Route as VaultSlugWithdrawRouteImport } from './routes/vault/$slug/withdraw'
import { Route as VaultSlugDepositRouteImport } from './routes/vault/$slug/deposit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/admin/new',
  path: '/admin/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVaultIdRoute = AdminVaultIdRouteImport.update({
  id: '/admin/$vaultId',
  path: '/admin/$vaultId',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultSlugWithdrawRoute = VaultSlugWithdrawRouteImport.update({
  id: '/vault/$slug/withdraw',
  path: '/vault/$slug/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultSlugDepositRoute = VaultSlugDepositRouteImport.update({
  id: '/vault/$slug/deposit',
  path: '/vault/$slug/deposit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$vaultId': typeof AdminVaultIdRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/vault/$slug/deposit': typeof VaultSlugDepositRoute
  '/vault/$slug/withdraw': typeof VaultSlugWithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$vaultId': typeof AdminVaultIdRoute
  '/admin/new': typeof AdminNewRoute
  '/admin': typeof AdminIndexRoute
  '/vault/$slug/deposit': typeof VaultSlugDepositRoute
  '/vault/$slug/withdraw': typeof VaultSlugWithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/$vaultId': typeof AdminVaultIdRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/': typeof AdminIndexRoute
  '/vault/$slug/deposit': typeof VaultSlugDepositRoute
  '/vault/$slug/withdraw': typeof VaultSlugWithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/$vaultId'
    | '/admin/new'
    | '/admin/'
    | '/vault/$slug/deposit'
    | '/vault/$slug/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/$vaultId'
    | '/admin/new'
    | '/admin'
    | '/vault/$slug/deposit'
    | '/vault/$slug/withdraw'
  id:
    | '__root__'
    | '/'
    | '/admin/$vaultId'
    | '/admin/new'
    | '/admin/'
    | '/vault/$slug/deposit'
    | '/vault/$slug/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminVaultIdRoute: typeof AdminVaultIdRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  VaultSlugDepositRoute: typeof VaultSlugDepositRoute
  VaultSlugWithdrawRoute: typeof VaultSlugWithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/admin/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$vaultId': {
      id: '/admin/$vaultId'
      path: '/admin/$vaultId'
      fullPath: '/admin/$vaultId'
      preLoaderRoute: typeof AdminVaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$slug/withdraw': {
      id: '/vault/$slug/withdraw'
      path: '/vault/$slug/withdraw'
      fullPath: '/vault/$slug/withdraw'
      preLoaderRoute: typeof VaultSlugWithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$slug/deposit': {
      id: '/vault/$slug/deposit'
      path: '/vault/$slug/deposit'
      fullPath: '/vault/$slug/deposit'
      preLoaderRoute: typeof VaultSlugDepositRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminVaultIdRoute: AdminVaultIdRoute,
  AdminNewRoute: AdminNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  VaultSlugDepositRoute: VaultSlugDepositRoute,
  VaultSlugWithdrawRoute: VaultSlugWithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
